apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: d6ea79e47cd015b3d0aa284e1f385ca8bbccc4f9de8e104227d27b810b0449d8
    cni.projectcalico.org/podIP: 10.244.0.21/32
    cni.projectcalico.org/podIPs: 10.244.0.21/32
    kubectl.kubernetes.io/restartedAt: "2026-06-29T09:06:58+05:30"
    zt-xguard.io/expected-spiffe-id: spiffe://oran.fyp.local/ns/ricxapp/sa/ricxapp-kpimon-go
    zt-xguard.io/svid-logger-version: v2-configmap
  creationTimestamp: "2026-06-29T03:36:59Z"
  generateName: ricxapp-kpimon-go-8554c49c64-
  generation: 1
  labels:
    app: ricxapp-kpimon-go
    kubernetes_name: ricxapp_kpimon-go
    pod-template-hash: 8554c49c64
    release: kpimon-go
    security-status: trusted
    zt-xguard.io/identity-managed: "true"
    zt-xguard.io/svid-enabled: "true"
  name: ricxapp-kpimon-go-8554c49c64-5v8sd
  namespace: ricxapp
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ricxapp-kpimon-go-8554c49c64
    uid: 5da1cef6-c5e1-4122-be5c-fa55937ee76a
  resourceVersion: "1331514"
  uid: 3b6ea7a0-506e-48ff-95ec-099cd1d33564
spec:
  containers:
  - env:
    - name: OCUDU_CELL_HEX
      value: 00066c0000
    - name: OCUDU_PLMN_HEX
      value: 00f110
    envFrom:
    - configMapRef:
        name: configmap-ricxapp-kpimon-go-appenv
    - configMapRef:
        name: dbaas-appconfig
    image: 127.0.0.1:80/kpimon-ocudu-cell:ztx-experiment-v1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: ric/v1/health/alive
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    name: kpimon-go
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 4560
      name: rmr-data
      protocol: TCP
    - containerPort: 4561
      name: rmr-route
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: ric/v1/health/ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/svid
      name: svid-data
      readOnly: true
    - mountPath: /opt/ric/config
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
  - args:
    - /opt/ztx/svid-renew.sh
    command:
    - /bin/sh
    env:
    - name: EXPECTED_SPIFFE_ID
      value: spiffe://oran.fyp.local/ns/ricxapp/sa/ricxapp-kpimon-go
    - name: RENEW_INTERVAL_SECONDS
      value: "60"
    image: docker.io/library/zt-spire-fetcher:1.0
    imagePullPolicy: IfNotPresent
    name: renew-svid
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/ztx/svid-renew.sh
      name: svid-renew-logger
      readOnly: true
      subPath: svid-renew.sh
    - mountPath: /run/spire/sockets
      name: spiffe-socket
      readOnly: true
    - mountPath: /etc/svid
      name: svid-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: kpimon-go
  imagePullSecrets:
  - name: 127-0-0-1-80
  initContainers:
  - args:
    - |
      SOCKET=/run/spire/sockets/spire-agent.sock
      OUTPUT=/etc/svid

      echo "Waiting for SPIRE socket..."

      for i in $(seq 1 60); do
        [ -S "$SOCKET" ] && break
        echo "Socket not ready: $i/60"
        sleep 2
      done

      test -S "$SOCKET"
      mkdir -p "$OUTPUT"

      echo "Waiting for workload identity..."

      for i in $(seq 1 60); do
        if /opt/spire/bin/spire-agent api fetch x509                      -socketPath "$SOCKET"                      -write "$OUTPUT"
        then
          chmod 0644 "$OUTPUT/svid.0.pem"
          chmod 0600 "$OUTPUT/svid.0.key"
          chmod 0644 "$OUTPUT/bundle.0.pem"

          echo "SVID_FETCH_OK"
          exit 0
        fi

        echo "Identity not ready: $i/60"
        sleep 2
      done

      echo "SVID_FETCH_FAILED"
      exit 1
    command:
    - /bin/sh
    - -ec
    image: docker.io/library/zt-spire-fetcher:1.0
    imagePullPolicy: IfNotPresent
    name: fetch-svid
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/spire/sockets
      name: spiffe-socket
      readOnly: true
    - mountPath: /etc/svid
      name: svid-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
  nodeName: near-rt-ric
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ricxapp-kpimon-go
  serviceAccountName: ricxapp-kpimon-go
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 365
      name: zt-xguard-svid-renew-logger
    name: svid-renew-logger
  - csi:
      driver: csi.spiffe.io
      readOnly: true
    name: spiffe-socket
  - emptyDir: {}
    name: svid-data
  - configMap:
      defaultMode: 420
      name: configmap-ricxapp-kpimon-go-appconfig
    name: config-volume
  - name: kube-api-access-wwq8v
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T03:37:05Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T03:37:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T03:37:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T03:37:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T03:36:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 10m
      memory: 32Mi
    containerID: containerd://c7eaa3df148c01f03a4f12501f69940621e4f1d9ae7efa9df4b170ea58b324d6
    image: 127.0.0.1:80/kpimon-ocudu-cell:ztx-experiment-v1
    imageID: 127.0.0.1:80/kpimon-ocudu-cell@sha256:47833746e5d1d1b32f339c218e9fe87b8eb180ae5ee789793a18717b00bb570a
    lastState: {}
    name: kpimon-go
    ready: true
    resources:
      limits:
        cpu: 200m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-29T03:37:07Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /etc/svid
      name: svid-data
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /opt/ric/config
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
      recursiveReadOnly: Disabled
  - allocatedResources:
      cpu: 5m
      memory: 16Mi
    containerID: containerd://7c86d7e403300927147bb3f55af926360801145b08ad07f325be656ed4b2cdc9
    image: docker.io/library/zt-spire-fetcher:1.0
    imageID: sha256:9bbdbf322cd7dd145f00f60dfb1c3bd03e48bb37e23ace9728f28a03cfbb7753
    lastState: {}
    name: renew-svid
    ready: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-29T03:37:09Z"
    user:
      linux:
        gid: 10001
        supplementalGroups:
        - 10001
        uid: 10001
    volumeMounts:
    - mountPath: /opt/ztx/svid-renew.sh
      name: svid-renew-logger
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /run/spire/sockets
      name: spiffe-socket
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /etc/svid
      name: svid-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.8.159
  hostIPs:
  - ip: 192.168.8.159
  initContainerStatuses:
  - allocatedResources:
      cpu: 5m
      memory: 16Mi
    containerID: containerd://37421a917e784d5d9f8ebcf7caaee76e0c3d7f8e4ff5a2309a336dab12033fa3
    image: docker.io/library/zt-spire-fetcher:1.0
    imageID: sha256:9bbdbf322cd7dd145f00f60dfb1c3bd03e48bb37e23ace9728f28a03cfbb7753
    lastState: {}
    name: fetch-svid
    ready: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 16Mi
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://37421a917e784d5d9f8ebcf7caaee76e0c3d7f8e4ff5a2309a336dab12033fa3
        exitCode: 0
        finishedAt: "2026-06-29T03:37:06Z"
        reason: Completed
        startedAt: "2026-06-29T03:37:04Z"
    user:
      linux:
        gid: 10001
        supplementalGroups:
        - 10001
        uid: 10001
    volumeMounts:
    - mountPath: /run/spire/sockets
      name: spiffe-socket
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /etc/svid
      name: svid-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wwq8v
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 10.244.0.21
  podIPs:
  - ip: 10.244.0.21
  qosClass: Burstable
  startTime: "2026-06-29T03:36:59Z"
