apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: f586e20bc2e3f562d8062c2763258fdb0dacaded83dee067cd808a59cbd58799
    cni.projectcalico.org/podIP: 10.244.0.117/32
    cni.projectcalico.org/podIPs: 10.244.0.117/32
    kubectl.kubernetes.io/restartedAt: "2026-06-30T14:07:10+05:30"
  creationTimestamp: "2026-06-30T08:37:10Z"
  generateName: caldera-agent-6d6c6c886f-
  generation: 1
  labels:
    app: caldera-agent
    pod-template-hash: 6d6c6c886f
    zt-xguard.io/component: adversary-emulation
  name: caldera-agent-6d6c6c886f-nbhqj
  namespace: caldera-lab
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: caldera-agent-6d6c6c886f
    uid: b0834bf1-fcb3-4416-8900-ecd1f208a642
  resourceVersion: "1424522"
  uid: 2608f327-1827-4988-994c-b4d482df9efa
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/sh
    - /config/start.sh
    env:
    - name: CALDERA_URL
      value: http://192.168.8.142:8888
    - name: AGENT_GROUP
      value: ztx-cluster-lab
    - name: AGENT_PAW
      value: ztx-cluster-agent-02
    - name: HOME
      value: /tmp
    - name: ZTX_ACTUATOR_TOKEN
      valueFrom:
        secretKeyRef:
          key: ZTX_ACTUATOR_TOKEN
          name: ztx-caldera-actuator-token
    image: curlimages/curl:8.11.1
    imagePullPolicy: IfNotPresent
    name: sandcat
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: startup
      readOnly: true
    - mountPath: /work
      name: work
    - mountPath: /tmp
      name: temporary
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: near-rt-ric
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsNonRoot: true
    runAsUser: 100
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: caldera-agent
  serviceAccountName: caldera-agent
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 365
      name: caldera-agent-start
    name: startup
  - emptyDir: {}
    name: work
  - emptyDir: {}
    name: temporary
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-30T08:37:12Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-06-30T08:37:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-30T08:37:12Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-30T08:37:12Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-30T08:37:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 25m
      memory: 32Mi
    containerID: containerd://0a6cf49d364f35c4d4e80cca71fe5bee335aaac1f8eb7edff3f65121bdd460c4
    image: docker.io/curlimages/curl:8.11.1
    imageID: docker.io/curlimages/curl@sha256:c1fe1679c34d9784c1b0d1e5f62ac0a79fca01fb6377cdd33e90473c6f9f9a69
    lastState: {}
    name: sandcat
    ready: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-30T08:37:12Z"
    user:
      linux:
        gid: 101
        supplementalGroups:
        - 101
        uid: 100
    volumeMounts:
    - mountPath: /config
      name: startup
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /work
      name: work
    - mountPath: /tmp
      name: temporary
  hostIP: 192.168.8.159
  hostIPs:
  - ip: 192.168.8.159
  phase: Running
  podIP: 10.244.0.117
  podIPs:
  - ip: 10.244.0.117
  qosClass: Burstable
  startTime: "2026-06-30T08:37:10Z"
