apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 4005fd77932165c13c16ac8c80a1a40be3681745d654ec2fa2a3011056e35b9e
    cni.projectcalico.org/podIP: 10.244.0.38/32
    cni.projectcalico.org/podIPs: 10.244.0.38/32
    kubectl.kubernetes.io/restartedAt: "2026-07-01T21:19:15+05:30"
  creationTimestamp: "2026-07-02T04:20:18Z"
  generateName: caldera-agent-86f5b6dc98-
  generation: 1
  labels:
    app: caldera-agent
    pod-template-hash: 86f5b6dc98
    zt-xguard.io/component: adversary-emulation
  name: caldera-agent-86f5b6dc98-p4z6z
  namespace: caldera-lab
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: caldera-agent-86f5b6dc98
    uid: 8f51a251-2ece-4287-84bb-398e6feb0120
  resourceVersion: "1513627"
  uid: fd840d42-6354-4905-9223-28fdf116fa44
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/sh
    - /config/start.sh
    env:
    - name: CALDERA_URL
      value: http://192.168.8.142:8888
    - name: AGENT_GROUP
      value: ztx-cluster-lab
    - name: AGENT_PAW
      value: ztx-cluster-agent-singlelink-20260701154914
    - name: HOME
      value: /tmp
    - name: ZTX_ACTUATOR_TOKEN
      valueFrom:
        secretKeyRef:
          key: ZTX_ACTUATOR_TOKEN
          name: ztx-caldera-actuator-token
    - name: CALDERA_PAW
      value: ztx-cluster-agent-20260701040203
    - name: CALDERA_GROUP
      value: ztx-cluster-lab
    - name: CALDERA_SERVER
      value: http://192.168.8.142:8888
    - name: PAW
      value: ztx-cluster-agent-20260701040203
    - name: group
      value: ztx-cluster-lab
    - name: GROUP
      value: ztx-cluster-lab
    - name: server
      value: http://192.168.8.142:8888
    - name: SERVER
      value: http://192.168.8.142:8888
    image: curlimages/curl:8.11.1
    imagePullPolicy: IfNotPresent
    name: sandcat
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: startup
      readOnly: true
    - mountPath: /work
      name: work
    - mountPath: /tmp
      name: temporary
    - mountPath: /opt/ztx/ztx_singlelink_pilot.sh
      name: ztx-singlelink-pilot
      readOnly: true
      subPath: ztx_singlelink_pilot.sh
    - mountPath: /opt/ztx/ztx_caldera_safe900.sh
      name: ztx-safe900
      readOnly: true
      subPath: ztx_caldera_safe900.sh
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: near-rt-ric
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsNonRoot: true
    runAsUser: 100
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: caldera-agent
  serviceAccountName: caldera-agent
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 365
      name: caldera-agent-start
    name: startup
  - emptyDir: {}
    name: work
  - emptyDir: {}
    name: temporary
  - configMap:
      defaultMode: 493
      name: ztx-caldera-singlelink-pilot
    name: ztx-singlelink-pilot
  - configMap:
      defaultMode: 493
      name: ztx-caldera-safe900
    name: ztx-safe900
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-02T04:20:21Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-02T04:20:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-02T04:20:21Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-02T04:20:21Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-02T04:20:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 25m
      memory: 32Mi
    containerID: containerd://24a3089e87475d3abc805abc5524460aad3c426073e9b5ac768f7a8109e83734
    image: docker.io/curlimages/curl:8.11.1
    imageID: docker.io/curlimages/curl@sha256:c1fe1679c34d9784c1b0d1e5f62ac0a79fca01fb6377cdd33e90473c6f9f9a69
    lastState: {}
    name: sandcat
    ready: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 32Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-02T04:20:20Z"
    user:
      linux:
        gid: 101
        supplementalGroups:
        - 101
        uid: 100
    volumeMounts:
    - mountPath: /config
      name: startup
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /work
      name: work
    - mountPath: /tmp
      name: temporary
    - mountPath: /opt/ztx/ztx_singlelink_pilot.sh
      name: ztx-singlelink-pilot
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /opt/ztx/ztx_caldera_safe900.sh
      name: ztx-safe900
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.8.159
  hostIPs:
  - ip: 192.168.8.159
  phase: Running
  podIP: 10.244.0.38
  podIPs:
  - ip: 10.244.0.38
  qosClass: Burstable
  startTime: "2026-07-02T04:20:18Z"
