apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: r4-submgr
    meta.helm.sh/release-namespace: ricplt
  creationTimestamp: "2026-05-30T05:47:41Z"
  labels:
    app: ricplt-submgr
    app.kubernetes.io/managed-by: Helm
    chart: submgr-3.0.0
    heritage: Helm
    release: r4-submgr
  name: service-ricplt-submgr-http
  namespace: ricplt
  resourceVersion: "1098"
  uid: 5cc07344-5ead-4836-8a04-c9751b73f36c
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3800
    protocol: TCP
    targetPort: http
  selector:
    app: ricplt-submgr
    release: r4-submgr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
